from __future__ import annotations

ALL_PERMISSIONS = [
    {"key": "dashboard", "name": "仪表盘", "group": "页面权限", "type": "page"},
    {"key": "platforms", "name": "平台管理", "group": "页面权限", "type": "page"},
    {"key": "content", "name": "内容工坊", "group": "页面权限", "type": "page"},
    {"key": "publish", "name": "发布管理", "group": "页面权限", "type": "page"},
    {"key": "templates", "name": "模板中心", "group": "页面权限", "type": "page"},
    {"key": "review", "name": "内容审核", "group": "页面权限", "type": "page"},
    {"key": "sql_review", "name": "SQL 审核", "group": "页面权限", "type": "page"},
    {"key": "accounts", "name": "账号管理", "group": "页面权限", "type": "page"},
    {"key": "token_plan", "name": "Token 配置", "group": "页面权限", "type": "page"},
    {"key": "api_docs", "name": "API 文档", "group": "页面权限", "type": "page"},
    {"key": "database", "name": "数据库管理", "group": "页面权限", "type": "page"},
    {"key": "permission_manage", "name": "权限管理", "group": "页面权限", "type": "page"},
    {"key": "user_perm_manage", "name": "用户权限配置", "group": "页面权限", "type": "action"},
    {"key": "user:create", "name": "创建用户", "group": "系统设置", "type": "action"},
    {"key": "user:update", "name": "编辑用户", "group": "系统设置", "type": "action"},
    {"key": "user:delete", "name": "删除用户", "group": "系统设置", "type": "action"},
    {"key": "user:change_password", "name": "修改用户密码", "group": "系统设置", "type": "action"},
    {"key": "content:create", "name": "创建内容", "group": "内容管理", "type": "action"},
    {"key": "content:update", "name": "编辑内容", "group": "内容管理", "type": "action"},
    {"key": "content:delete", "name": "删除内容", "group": "内容管理", "type": "action"},
    {"key": "content:ai_generate", "name": "AI 生成", "group": "内容管理", "type": "action"},
    {"key": "review:submit", "name": "提交内容审核", "group": "审核管理", "type": "action"},
    {"key": "review:approve", "name": "审核通过", "group": "审核管理", "type": "action"},
    {"key": "review:reject", "name": "审核驳回", "group": "审核管理", "type": "action"},
    {"key": "db_change:submit", "name": "提交SQL变更", "group": "审核管理", "type": "action"},
    {"key": "db_change:approve", "name": "SQL变更审核通过", "group": "审核管理", "type": "action"},
    {"key": "db_change:reject", "name": "SQL变更驳回", "group": "审核管理", "type": "action"},
    {"key": "template:create", "name": "创建模板", "group": "内容管理", "type": "action"},
    {"key": "template:update", "name": "编辑模板", "group": "内容管理", "type": "action"},
    {"key": "template:delete", "name": "删除模板", "group": "内容管理", "type": "action"},
    {"key": "account:create", "name": "添加平台账号", "group": "基础", "type": "action"},
    {"key": "account:update", "name": "编辑平台账号", "group": "基础", "type": "action"},
    {"key": "account:delete", "name": "删除平台账号", "group": "基础", "type": "action"},
    {"key": "account:check", "name": "检测账号状态", "group": "基础", "type": "action"},
    {"key": "publish:create", "name": "创建发布任务", "group": "内容管理", "type": "action"},
    {"key": "publish:retry", "name": "重试发布任务", "group": "内容管理", "type": "action"},
    {"key": "model_config:create", "name": "创建模型配置", "group": "系统设置", "type": "action"},
    {"key": "model_config:update", "name": "编辑模型配置", "group": "系统设置", "type": "action"},
    {"key": "model_config:delete", "name": "删除模型配置", "group": "系统设置", "type": "action"},
    {"key": "db:execute", "name": "执行SQL命令", "group": "系统设置", "type": "action"},
    {"key": "db:history:read", "name": "查看SQL历史", "group": "系统设置", "type": "action"},
]

ALL_PERMISSION_KEYS = [p["key"] for p in ALL_PERMISSIONS]

ADMIN_ONLY_PERMISSIONS = [
    "user_perm_manage",
    "permission_manage",
    "database",
    "db:execute",
    "db:history:read",
    "model_config:create",
    "model_config:update",
    "model_config:delete",
    "user:delete",
]

DATABASE_PERMISSIONS = [
    "database",
    "db:execute",
    "db:history:read",
]

DEFAULT_ROLE_PERMISSIONS: dict[str, list[str]] = {
    "admin": ALL_PERMISSION_KEYS,
    "manager": [
        "dashboard", "platforms", "content", "publish", "templates", "review", "sql_review",
        "accounts", "token_plan", "api_docs", "permission_manage",
        "user:create", "user:update", "user:change_password", "user_perm_manage",
        "content:create", "content:update", "content:delete", "content:ai_generate",
        "review:submit", "review:approve", "review:reject",
        "db_change:submit", "db_change:approve", "db_change:reject",
        "template:create", "template:update", "template:delete",
        "account:create", "account:update", "account:delete", "account:check",
        "publish:create", "publish:retry",
    ],
    "operator": [
        "dashboard", "content", "publish", "templates", "platforms",
        "accounts", "token_plan", "api_docs",
        "user:create", "user:update", "user:change_password",
        "content:create", "content:update", "content:delete", "content:ai_generate",
        "review:submit",
        "db_change:submit",
        "template:create", "template:update", "template:delete",
        "account:create", "account:update", "account:delete", "account:check",
        "publish:create", "publish:retry",
    ],
    "reviewer": [
        "dashboard", "content", "review", "sql_review", "platforms",
        "review:approve", "review:reject",
        "db_change:approve", "db_change:reject",
        "template:create", "template:update", "template:delete",
    ],
}
